name: pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          clean: true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
